---

- name: load os specific vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- import_tasks: user_mgmt.yml

- import_tasks: config.yml

- import_tasks: service.yml

- meta: flush_handlers

- import_tasks: fw.yml
